/* ============================================================
   doyoudo 克隆 — 共享数据
   ============================================================ */

// ---------- 课程数据 (基于真实 doyoudo 课程结构) ----------
const coursesData = [
  { id:1, title:'最容易听懂的 PS 入门教程 - 从零基础到完全掌握', software:'ps', difficulty:'beginner', author:'李涛', duration:'8 小时', lessons:48, views:125000, isFree:true, price:0, rating:4.9, cover:'courses/course-01.jpg', desc:'本课程专为零基础学员设计，从 Photoshop 界面认识开始，逐步掌握图层、选区、蒙版、调色、滤镜等核心功能。', chapters:[{title:'认识 Photoshop 界面与基本操作',dur:'18:30'},{title:'图层的概念与基本操作',dur:'22:15'},{title:'选区工具的灵活运用',dur:'25:40'},{title:'蒙版入门 - 非破坏性编辑',dur:'20:10'},{title:'色彩调整与校色技巧',dur:'28:50'},{title:'文字工具与排版设计',dur:'16:20'},{title:'滤镜特效实战',dur:'24:00'},{title:'综合案例：海报设计全流程',dur:'35:15'}], relatedIds:[2,3,9,16] },
  { id:2, title:'PS 高级合成技巧 - 商业级图像处理实战', software:'ps', difficulty:'advanced', author:'李涛', duration:'12 小时', lessons:36, views:68000, isFree:false, price:299, rating:4.8, cover:'courses/course-02.jpg', desc:'面向有一定基础的设计师，深入学习高级合成、光影重塑、商业修图等专业技巧。', chapters:[{title:'高级选区与通道抠图',dur:'28:00'},{title:'光影理论与重塑',dur:'32:15'},{title:'商业人像精修流程',dur:'45:00'},{title:'多图合成与透视匹配',dur:'38:20'},{title:'电商海报合成实战',dur:'42:10'}], relatedIds:[1,3,16] },
  { id:3, title:'After Effects 动效设计 - 从入门到精通', software:'ae', difficulty:'intermediate', author:'王小兔', duration:'15 小时', lessons:60, views:98000, isFree:false, price:399, rating:4.9, cover:'courses/course-03.jpg', desc:'系统学习 AE 动效设计，涵盖关键帧动画、表达式、粒子系统、3D 图层、MG 动画等核心内容。', chapters:[{title:'AE 界面与工作流程',dur:'20:00'},{title:'关键帧动画基础',dur:'28:30'},{title:'形状图层与矢量动画',dur:'32:00'},{title:'文字动画与排版动效',dur:'25:40'},{title:'表达式入门',dur:'35:00'},{title:'粒子特效实战',dur:'40:20'},{title:'3D 图层与摄像机',dur:'38:10'},{title:'综合 MG 动画项目',dur:'50:00'}], relatedIds:[4,7,15] },
  { id:4, title:'AE 表达式完全指南 - 让动画更智能', software:'ae', difficulty:'advanced', author:'王小兔', duration:'6 小时', lessons:24, views:35000, isFree:false, price:249, rating:4.7, cover:'', desc:'深入 AE 表达式世界，学会用代码驱动动画，大幅提升工作效率。', chapters:[{title:'表达式语法基础',dur:'22:00'},{title:'wiggle 与随机动画',dur:'18:30'},{title:'loop 循环表达式',dur:'16:00'},{title:'time 与 index 的高级用法',dur:'20:40'},{title:'表达式控制与绑定',dur:'25:00'}], relatedIds:[3,7] },
  { id:5, title:'Premiere 剪辑入门 - 30 天成为剪辑达人', software:'pr', difficulty:'beginner', author:'张两万', duration:'10 小时', lessons:30, views:156000, isFree:true, price:0, rating:4.8, cover:'courses/course-04.jpg', desc:'30 天系统学习 PR 剪辑，每天一个小案例，涵盖素材管理、剪辑节奏、转场、调色、字幕、导出全流程。', chapters:[{title:'PR 界面与项目设置',dur:'15:00'},{title:'素材导入与管理',dur:'18:20'},{title:'基础剪辑工具与技巧',dur:'22:00'},{title:'转场特效大全',dur:'20:30'},{title:'音频处理与混音',dur:'25:00'},{title:'调色基础 - Lumetri 颜色',dur:'28:10'},{title:'字幕与标题制作',dur:'16:40'},{title:'导出设置与多平台适配',dur:'14:00'}], relatedIds:[6,13] },
  { id:6, title:'PR 高级剪辑工作流 - 专业级视频制作', software:'pr', difficulty:'advanced', author:'张两万', duration:'14 小时', lessons:42, views:52000, isFree:false, price:349, rating:4.6, cover:'', desc:'面向专业剪辑师的高级课程，涵盖多机位剪辑、代理工作流、协作剪辑、调色台使用等专业技巧。', chapters:[{title:'多机位同步剪辑',dur:'32:00'},{title:'代理剪辑工作流',dur:'25:00'},{title:'高级调色 - Lumetri 深入',dur:'40:00'},{title:'动态链接 - PR 与 AE 协作',dur:'28:30'},{title:'VR 视频剪辑',dur:'35:00'}], relatedIds:[5,13] },
  { id:7, title:'C4D 三维设计入门 - 创造你的第一个 3D 作品', software:'c4d', difficulty:'beginner', author:'郭八两', duration:'9 小时', lessons:36, views:89000, isFree:true, price:0, rating:4.9, cover:'', desc:'零基础学习 Cinema 4D，从建模到渲染，每个知识点都配有趣味小练习。', chapters:[{title:'C4D 界面与导航',dur:'16:00'},{title:'参数化建模基础',dur:'22:30'},{title:'样条线与生成器',dur:'24:00'},{title:'变形器与效果器',dur:'28:10'},{title:'灯光与材质基础',dur:'20:00'},{title:'渲染设置与输出',dur:'18:40'}], relatedIds:[8,3] },
  { id:8, title:'C4D 动态图形 - Redshift 渲染实战', software:'c4d', difficulty:'advanced', author:'郭八两', duration:'16 小时', lessons:48, views:41000, isFree:false, price:499, rating:4.8, cover:'', desc:'C4D 动态图形设计与 Redshift GPU 渲染器专业课程，专注商业级 3D 动画制作。', chapters:[{title:'MoGraph 核心概念',dur:'30:00'},{title:'效果器深度应用',dur:'35:20'},{title:'Redshift 材质系统',dur:'42:00'},{title:'灯光与 HDRI 照明',dur:'28:30'},{title:'商业渲染案例全流程',dur:'55:00'}], relatedIds:[7,3] },
  { id:9, title:'Illustrator 矢量插画 - 画出你的创意世界', software:'ai', difficulty:'beginner', author:'孙小美', duration:'7 小时', lessons:28, views:72000, isFree:true, price:0, rating:4.7, cover:'', desc:'从零开始学 AI，掌握钢笔工具、形状生成器、渐变网格等核心功能，画出专业矢量插画。', chapters:[{title:'AI 界面与文档设置',dur:'14:00'},{title:'钢笔工具完全掌握',dur:'28:00'},{title:'形状生成器与路径查找器',dur:'20:00'},{title:'色彩与渐变',dur:'18:30'},{title:'文字排版与字体设计',dur:'22:00'},{title:'插画创作全流程',dur:'35:00'}], relatedIds:[1,10] },
  { id:10, title:'AI 品牌 VI 设计 - 从 Logo 到视觉系统', software:'ai', difficulty:'intermediate', author:'孙小美', duration:'11 小时', lessons:32, views:45000, isFree:false, price:329, rating:4.8, cover:'', desc:'系统学习品牌 VI 设计全流程，涵盖 Logo 设计、色彩系统、字体规范、应用延展等内容。', chapters:[{title:'品牌设计方法论',dur:'20:00'},{title:'Logo 设计实战',dur:'35:00'},{title:'色彩体系构建',dur:'25:00'},{title:'字体与排版规范',dur:'22:30'},{title:'VI 手册制作',dur:'40:00'}], relatedIds:[9,1] },
  { id:11, title:'Audition 音频后期 - 让声音更动听', software:'au', difficulty:'beginner', author:'赵小声', duration:'5 小时', lessons:20, views:31000, isFree:true, price:0, rating:4.5, cover:'', desc:'零基础学 Audition，涵盖录音、降噪、混音、音效设计等音频后期处理核心技能。', chapters:[{title:'AU 界面与音频基础',dur:'16:00'},{title:'录音技巧与设备选择',dur:'22:00'},{title:'降噪与修复工具',dur:'20:00'},{title:'多轨混音实战',dur:'28:00'},{title:'音效设计与输出',dur:'18:00'}], relatedIds:[5,3] },
  { id:12, title:'FL Studio 电子音乐制作 - 从节拍到完整编曲', software:'fl', difficulty:'intermediate', author:'赵小声', duration:'13 小时', lessons:40, views:56000, isFree:false, price:369, rating:4.7, cover:'', desc:'学习 FL Studio 电子音乐制作，涵盖鼓组编排、合成器、混音、母带处理等完整流程。', chapters:[{title:'FL Studio 工作流程',dur:'18:00'},{title:'鼓组编排与节奏设计',dur:'25:00'},{title:'合成器与音色设计',dur:'32:00'},{title:'和弦进行与旋律创作',dur:'28:30'},{title:'混音与母带处理',dur:'35:00'}], relatedIds:[11] },
  { id:13, title:'Final Cut Pro 剪辑完全指南', software:'fcp', difficulty:'beginner', author:'张两万', duration:'8 小时', lessons:32, views:48000, isFree:true, price:0, rating:4.6, cover:'', desc:'专为 Mac 用户打造的 FCP 剪辑课程，涵盖磁性时间线、角色管理、颜色分级等独家功能。', chapters:[{title:'FCP 界面与媒体管理',dur:'15:00'},{title:'磁性时间线深入',dur:'22:00'},{title:'转场与效果',dur:'18:30'},{title:'颜色分级工具',dur:'24:00'},{title:'多平台导出优化',dur:'12:00'}], relatedIds:[5,6] },
  { id:14, title:'Lightroom 摄影后期 - 让每张照片都出彩', software:'lr', difficulty:'beginner', author:'陈大光', duration:'6 小时', lessons:24, views:64000, isFree:true, price:0, rating:4.8, cover:'', desc:'从零学 Lightroom，掌握曝光调整、色彩分级、局部修饰、批量处理等摄影后期核心技能。', chapters:[{title:'LR 图库管理与导入',dur:'16:00'},{title:'基本调整与曝光修正',dur:'22:00'},{title:'色彩分级与色调风格',dur:'25:00'},{title:'局部调整工具',dur:'18:00'},{title:'批量导出与预设',dur:'14:00'}], relatedIds:[1,9] },
  { id:15, title:'AE + C4D 联合创作 - 动态设计工作流', software:'ae', difficulty:'advanced', author:'王小兔', duration:'18 小时', lessons:52, views:38000, isFree:false, price:599, rating:4.9, cover:'', desc:'AE 与 C4D 联合创作课程，学习 Cineware 桥接、3D 元素合成、动态追踪等高级技巧。', chapters:[{title:'AE 与 C4D 桥接基础',dur:'22:00'},{title:'Cineware 工作流优化',dur:'28:00'},{title:'3D 摄像机追踪',dur:'35:00'},{title:'动态元素合成实战',dur:'42:00'},{title:'综合商业项目全流程',dur:'60:00'}], relatedIds:[3,8] },
  { id:16, title:'PS 电商设计实战 - 详情页与主图制作', software:'ps', difficulty:'intermediate', author:'李涛', duration:'9 小时', lessons:30, views:83000, isFree:false, price:259, rating:4.7, cover:'', desc:'专注电商视觉设计，涵盖详情页布局、主图设计、banner 制作、直通车图等电商核心视觉。', chapters:[{title:'电商设计规范与尺寸',dur:'16:00'},{title:'主图设计策略',dur:'24:00'},{title:'详情页布局与视觉引导',dur:'32:00'},{title:'促销 Banner 设计',dur:'28:00'},{title:'移动端适配技巧',dur:'20:00'}], relatedIds:[1,2] },
];

// ---------- 学习路径数据 ----------
const learningPathsData = [
  { id:'ps', software:'ps', icon:'Ps', title:'Photoshop 学习路径', desc:'从零基础到商业级图像处理高手，系统掌握 Photoshop 全部核心技能。', color:'sw-ps', stages:[{name:'入门基础',desc:'界面认识、基本工具、图层概念'},{name:'核心技能',desc:'选区、蒙版、调色、滤镜'},{name:'进阶实战',desc:'合成、修图、海报设计'},{name:'商业精通',desc:'品牌 VI、电商设计、创意合成'}], totalLessons:162, totalDuration:'36 小时', courseCount:3 },
  { id:'ae', software:'ae', icon:'Ae', title:'After Effects 学习路径', desc:'从关键帧动画到 MG 动效大师，全面掌握 AE 动态设计能力。', color:'sw-ae', stages:[{name:'入门基础',desc:'界面、图层、关键帧动画'},{name:'核心技能',desc:'形状动画、文字动效、表达式'},{name:'进阶实战',desc:'粒子系统、3D 图层、摄像机'},{name:'商业精通',desc:'MG 动画、广告包装、特效合成'}], totalLessons:136, totalDuration:'34 小时', courseCount:3 },
  { id:'pr', software:'pr', icon:'Pr', title:'Premiere 学习路径', desc:'从基础剪辑到专业级视频制作，系统培养剪辑思维与技术能力。', color:'sw-pr', stages:[{name:'入门基础',desc:'界面、素材管理、基础剪辑'},{name:'核心技能',desc:'转场、音频、调色、字幕'},{name:'进阶实战',desc:'多机位、代理、动态链接'},{name:'商业精通',desc:'纪录片、广告、短视频全流程'}], totalLessons:104, totalDuration:'32 小时', courseCount:2 },
  { id:'c4d', software:'c4d', icon:'4D', title:'Cinema 4D 学习路径', desc:'从三维建模到动态图形渲染，成为 3D 设计领域的专业人才。', color:'sw-c4d', stages:[{name:'入门基础',desc:'界面导航、参数化建模、样条线'},{name:'核心技能',desc:'变形器、材质、灯光、渲染'},{name:'进阶实战',desc:'MoGraph、动态图形、角色动画'},{name:'商业精通',desc:'Redshift 渲染、产品动画、舞台视觉'}], totalLessons:120, totalDuration:'34 小时', courseCount:2 },
  { id:'ai', software:'ai', icon:'Ai', title:'Illustrator 学习路径', desc:'从矢量绘图到品牌 VI 设计，全面掌握矢量设计核心能力。', color:'sw-ai', stages:[{name:'入门基础',desc:'界面、钢笔工具、形状工具'},{name:'核心技能',desc:'色彩、渐变、文字排版'},{name:'进阶实战',desc:'插画创作、图标设计、图案'},{name:'商业精通',desc:'品牌 VI、包装设计、信息图表'}], totalLessons:92, totalDuration:'25 小时', courseCount:2 },
  { id:'au', software:'au', icon:'Au', title:'Audition 学习路径', desc:'从音频录制到专业混音，掌握声音后期处理全流程。', color:'sw-au', stages:[{name:'入门基础',desc:'音频基础、界面、录音'},{name:'核心技能',desc:'降噪、均衡、压缩、混响'},{name:'进阶实战',desc:'多轨混音、音效设计'},{name:'商业精通',desc:'广播级混音、影视音频后期'}], totalLessons:56, totalDuration:'14 小时', courseCount:1 },
  { id:'fl', software:'fl', icon:'FL', title:'FL Studio 学习路径', desc:'从节拍制作到完整编曲，开启电子音乐创作之旅。', color:'sw-fl', stages:[{name:'入门基础',desc:'界面、钢琴卷帘、节拍制作'},{name:'核心技能',desc:'合成器、采样、混音器'},{name:'进阶实战',desc:'编曲结构、音色设计'},{name:'商业精通',desc:'母带处理、发行准备'}], totalLessons:68, totalDuration:'18 小时', courseCount:1 },
  { id:'fcp', software:'fcp', icon:'Fc', title:'Final Cut Pro 学习路径', desc:'Mac 平台专业剪辑，从磁性时间线到多平台输出。', color:'sw-fcp', stages:[{name:'入门基础',desc:'界面、媒体管理、磁性时间线'},{name:'核心技能',desc:'转场、字幕、颜色分级'},{name:'进阶实战',desc:'多机位、角色、复合片段'},{name:'商业精通',desc:'影视级剪辑工作流'}], totalLessons:32, totalDuration:'8 小时', courseCount:1 },
];

// ---------- 软件列表 ----------
const softwareList = [
  { id:'all', name:'全部', icon:'' },
  { id:'ps', name:'PS', icon:'' },
  { id:'ae', name:'AE', icon:'' },
  { id:'pr', name:'PR', icon:'' },
  { id:'c4d', name:'C4D', icon:'' },
  { id:'ai', name:'AI', icon:'' },
  { id:'au', name:'AU', icon:'' },
  { id:'fl', name:'FL', icon:'' },
  { id:'lr', name:'LR', icon:'' },
  { id:'fcp', name:'FCP', icon:'' },
];

// ---------- 难度标签映射 ----------
const diffLabels = { beginner:'初级', intermediate:'中级', advanced:'高级' };
const diffClasses = { beginner:'beginner', intermediate:'intermediate', advanced:'advanced' };
